# Generated by Django 5.0.6 on 2024-05-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото перевала'),
        ),
        migrations.AlterField(
            model_name='images',
            name='mountain_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='MPass.mountain'),
        ),
    ]
